config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "stories#home"
  get "/help" , to: "stories#help"

  resources :users
  get "/signup" , to: "users#new"
  post "/signup" ,to: "users#create"

  get "/login" ,to: "sessions#new"
  post "/login" ,to: "sessions#create"

delete "/logout" , to: "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/story.rb
class Story < ApplicationRecord

  
end

app/models/user.rb
class User < ApplicationRecord
  before_save {
    self.email = email.downcase
  }
    validates :name , presence: true , length: {minimum: 5}
   VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

   validates :email, presence: true , uniqueness: true, format:
   {with: VALID_EMAIL_REGEX}

   has_secure_password
  validates :password , length: {minimum: 6 , maximum: 20}, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
   end

   def create
     user = User.find_by(email: params[:session][:email])
     if user && user.authenticate(params[:session][:password])
      log_in user
      flash[:success] = "Heloo"
      redirect_to root_url
     else
       flash[:warning] = "Invalid Email or Password"
       render 'new'
     end
   end

   def destroy
    log_out user
    flash[:success] = " Bye bye "
    redirect_to root_url
   end


end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

def home
  
end

def help
  
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

 def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
     #byebug
     #@user = User.create name: ""
    @user = User.new user_params
    if @user.save
     #flash[:info] = "success"
     #redirect_to root_url
     flash[:success] = "Welcome to the Sample App!"
     #log_in @user
     redirect_to "/users/#{@user.id}"
     #redirect_to users_path(@user)
    else
     render :new
    end
  end


  private

  def user_params
    params.require(:user).permit(:name , :email, :password, :password_confirmation)
  end

  def authenticate
    return if logged_in?
    flash[:danger] = "You Do Not Permissions !!"
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Blog Of Things"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def logged_in?
    session[:user_id].present?
  end

  def current_user
    User.find_by(id: session[:user_id]) if logged_in?

  end

  def log_in user
    session[:user_id] = user.id
  end

  def log_out
    forget current_user
    session.delete :user_id
    @current_user = nil
  end


end

app/helpers/stories_helper.rb
module StoriesHelper
  
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a https://www.facebook.com/duynguyen.7397">Author</a>
    <h8>Duy Nguyen</h8> </a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   'https://www.facebook.com/duynguyen.7397' %></li>
      <li><%= link_to "Contact", 'https://www.facebook.com/duynguyen.7397' %></li>
      <li><a href="https://vnexpress.net/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "BLOG",  root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",  root_path %></li>
            <li><%= link_to "Help",   help_path %></li>
            <% if logged_in? %>
          <li><%= link_to "Users", "/users" %></li>
          <li class="dropdown">
            <a href="#" data-toggle="dropdown">
              <%= "#{current_user.name}"%><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", "/users/#{current_user.id}/edit" %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
          </ul>
        </nav>
      </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield :title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    <body>
    <%= render "layouts/header" %>

    <div class="container">
       <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>

  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/stories/help.html.erb
<h1>Help</h1>

app/views/stories/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
  <h1>Welcome to the Blog</h1>

  <h2>
    This is the home page for the Blog Of Things
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user , url: signup_path) do |f|%>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control'%>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      <br>
      <%= f.submit "Create my account", class: "btn btn-primary" %>
      <br>
      <br>
      <%= f.label "Have you account?" %>
      <%= link_to "Click Here", login_path %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>